// Edit siteNames to include the landmarks you desire
// This will affect the labels that users can choose from when collecting and uploading data

const siteNames = [
    'Alderman Library',
    'Aquatic and Fitness Center',
    'Astronomy Building',
    'Birdwood Golf Course',
    'Bayly Building',
    'Brooks Hall',
    'Bryan Hall',
    'Brown College Library',
    'Bryant Hall',
    'New Cabell Hall',
    'Campbell Hall',
    'Cauthen House',
    'Chemical Engineering Building',
    'Claude Moore Nursing',
    'Cobb Hall',
    'Cocke Hall',
    'Chemistry Building',
    'Clark Hall',
    'Clemons Library',
    'Dell 1',
    'Dell 2',
    "Dawson's Row Residence 1",
    'Drama Education Building',
    'Hospital West, Davis Wing',
    'Fayerweather Hall',
    'French House',
    'Gibson Hall',
    'Gilmer Hall',
    'Darden School',
    'Halsey Hall',
    'Hotel D, East Range',
    'Home of the Instructor',
    'Charlottesville Ice Park',
    'International Study program outside the U.S.',
    'Judge Advocate General School',
    'Jordan Hall',
    'Kerchof Hall',
    'Levering Hall',
    'Lambeth House',
    'Luther P. Jackson House',
    'Lower West Oval Room, Rotunda',
    'McLeod Hall',
    'Mechanical Engineering Building',
    'Old Medical School',
    'Memorial Gymnasium',
    'Multistory Building',
    'Monroe Hill Range',
    'Minor Hall',
    'Monroe Hall',
    'Maury Hall',
    'Materials Science Building',
    'Mary Munford House',
    'Nau Hall',
    'Newcomb Hall',
    'No Room Needed',
    'UVA/VT Center in Falls Church',
    'McCormick Observatory',
    'Old Cabell Hall',
    'Olsson Hall',
    'Peabody Hall',
    'Physics Building',
    'Pavilion V',
    'Pavilion VIII',
    'Randall Hall',
    'National Radio Astronomy Observatory',
    'Robertson Hall',
    'Ridley Hall',
    'Nuclear Reactor',
    'Slaughter Recreation Center',
    'Rice Hall',
    'Rouss Hall',
    'Rotunda',
    'Ruffin Hall',
    'Shea House',
    'Shannon House',
    'Slaughter Hall',
    'Barracks Stables',
    'Stacey Hall',
    'Thornton Hall',
    'Wilson Hall',
    'Wintergreen Resort',
    'Withers-Brown Hall',
    'Zehmer Hall Annex',
    'Zehmer Hall'
]

const siteCodes = [
    'ALD',  'AQC',  'AST',  'BGC', 'BMU#', 'BRK#', 'BRN',
    'BRO',  'BRY',  'CAB',  'CAM', 'CAU',  'CHE',  'CMN',
    'COB',  'COC',  'CHM#', 'CLK', 'CLM',  'DL1',  'DL2',
    'DR1*', 'DRM#', 'DVS',  'FHL', 'FRN*', 'GIB',  'GIL#',
    'GSB',  'HAL#', 'HOD*', 'HOM', 'ICE',  'ISO',  'JAG',
    'JOR#', 'KER#', 'LEV#', 'LHO', 'LPJ#', 'LWO',  'MCL',
    'MEC',  'MED',  'MGM#', 'MHP', 'MH3',  'MIN',  'MON',
    'MRY',  'MSB',  'MUN',  'NAU', 'NHL',  'NRN',  'NVA',
    'OBS*', 'OCH',  'OLS',  'PBY', 'PHS#', 'PV5',  'PV8*',
    'RAN#', 'RAO#', 'RBT',  'RDL', 'REA*', 'REC',  'RICE',
    'RSH',  'RTN',  'RUF',  'SHH', 'SHN',  'SLH',  'STB',
    'STC',  'THN#', 'WIL',  'WIN', 'WSB',  'ZMA',  'ZMR'
]


export { siteNames, siteCodes }